export const ErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  OWNERSHIP_REQUIRED: 'OWNERSHIP_REQUIRED',
  LAST_ADMIN_PROTECTED: 'LAST_ADMIN_PROTECTED',
  LESSON_ORDER_CONFLICT: 'LESSON_ORDER_CONFLICT',
  UPLOAD_LIMIT_EXCEEDED: 'UPLOAD_LIMIT_EXCEEDED',
  FORBIDDEN_ROLE: 'FORBIDDEN_ROLE',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
