export const LessonIndexErrorCode = {
  EXTRACTION_FAILED: 'LESSON_INDEX_EXTRACTION_FAILED',
  EMBEDDING_FAILED: 'LESSON_INDEX_EMBEDDING_FAILED',
  RAG_UNAVAILABLE: 'LESSON_INDEX_RAG_UNAVAILABLE',
  MEDIA_DOWNLOAD_FAILED: 'LESSON_INDEX_MEDIA_DOWNLOAD_FAILED',
  RAG_CALLBACK_FAILED: 'LESSON_INDEX_RAG_CALLBACK_FAILED',
} as const;

export type LessonIndexErrorCode =
  (typeof LessonIndexErrorCode)[keyof typeof LessonIndexErrorCode];
